import { Listing } from "./listings";

// Bundled copy of the 6 seed fiches under Products/<Category>/Listings/. Used
// ONLY when MOCK_DATA=1 or no GITHUB_TOKEN is set (local dev / CI verification),
// so the app renders real seed content without a token. The production path
// reads the identical fiches from GitHub via lib/github.ts. Keep in sync with
// the .md files — they are the source of truth.
const R2 = "https://pub-56803a79fa0e45e0a65f7deb9a50ee4c.r2.dev/seed/products";

export const MOCK_LISTINGS: Listing[] = [
  {
    type: "product-listing",
    layer: "products",
    created: "2026-07-12",
    updated: "2026-07-16",
    status: "Approved",
    slug: "sage-ceramic-mug",
    category: "Mugs",
    collection: "Minimalist Kitchen",
    store: null,
    title_etsy:
      "Sage Green Ceramic Coffee Mug — Minimalist Handmade Style Cup, 11oz & 15oz",
    description_long:
      "A calm, muted sage green ceramic mug for slow mornings. Glazed matte exterior, glossy interior, comfortable curved handle. Microwave and dishwasher safe. Printed and shipped on demand — each mug is made to order.",
    description_short: "Muted sage green ceramic mug, matte glaze, 11oz & 15oz.",
    tags: [
      "ceramic mug",
      "sage green mug",
      "minimalist mug",
      "coffee mug",
      "handmade style",
      "aesthetic mug",
      "cottagecore",
      "gift for her",
      "tea cup",
      "neutral kitchen",
    ],
    categories_etsy: [
      "Home & Living > Kitchen & Dining > Drinkware > Mugs",
    ],
    price: 24.0,
    currency: "USD",
    sku: "MUG-SAGE-001",
    pod_provider: "Printify",
    materials: ["ceramic"],
    variants: [{ name: "Size", options: ["11oz", "15oz"] }],
    colors: ["Sage Green"],
    sizes: ["11oz", "15oz"],
    images: [`${R2}/ceramic-mug-01.jpg`, `${R2}/ceramic-mug-02.jpg`],
    mockups: [],
    video_url: null,
    image_provider: "workers-ai",
    image_model: "@cf/black-forest-labs/flux-1-schnell",
    quality_score: 8.4,
    favorite: true,
    printify_product_id: null,
    etsy_listing_id: null,
    regeneration_requested: null,
    history: [
      { date: "2026-07-12T09:00:00Z", action: "created", actor: "seed", note: "Seed data" },
      { date: "2026-07-16T14:20:00Z", action: "approve", actor: "console", note: "Status Draft -> Approved" },
    ],
  },
  {
    type: "product-listing",
    layer: "products",
    created: "2026-07-18",
    updated: "2026-07-18",
    status: "Draft",
    slug: "midnight-cosmos-mug",
    category: "Mugs",
    collection: null,
    store: null,
    title_etsy:
      "Midnight Cosmos Galaxy Mug — Celestial 11oz Ceramic Coffee Cup, Astronomy Gift",
    description_long:
      "Deep space in your hands. A midnight-blue galaxy mug scattered with stars and nebula tones, for anyone who loves the night sky. Ceramic, microwave and dishwasher safe, made to order.",
    description_short: "Galaxy-print ceramic mug in midnight blue, 11oz.",
    tags: [
      "galaxy mug",
      "cosmos mug",
      "celestial gift",
      "astronomy mug",
      "space lover",
      "night sky",
      "ceramic mug",
      "coffee mug",
      "stars",
      "nebula",
    ],
    categories_etsy: ["Home & Living > Kitchen & Dining > Drinkware > Mugs"],
    price: 22.5,
    currency: "USD",
    sku: "MUG-COSMOS-002",
    pod_provider: "Printify",
    materials: ["ceramic"],
    variants: [{ name: "Size", options: ["11oz"] }],
    colors: ["Midnight Blue", "Black"],
    sizes: ["11oz"],
    images: [`${R2}/ceramic-mug-02.jpg`, `${R2}/ceramic-mug-01.jpg`],
    mockups: [],
    video_url: null,
    image_provider: "workers-ai",
    image_model: "@cf/black-forest-labs/flux-1-schnell",
    quality_score: null,
    favorite: false,
    printify_product_id: null,
    etsy_listing_id: null,
    regeneration_requested: null,
    history: [
      { date: "2026-07-18T08:10:00Z", action: "created", actor: "seed", note: "Seed data" },
    ],
  },
  {
    type: "product-listing",
    layer: "products",
    created: "2026-07-14",
    updated: "2026-07-17",
    status: "PublishRequested",
    slug: "cozy-knit-sweater",
    category: "Shirts",
    collection: "Autumn Knits",
    store: null,
    title_etsy:
      "Cozy Oversized Knit Sweater — Handmade-Style Wool Blend Pullover, Unisex",
    description_long:
      "An oversized, chunky-knit pullover in warm neutral tones — the sweater you live in from October onward. Soft wool-acrylic blend, ribbed cuffs and hem, relaxed unisex fit. Made to order.",
    description_short: "Oversized chunky-knit wool-blend pullover, unisex fit.",
    tags: [
      "knit sweater",
      "oversized sweater",
      "wool pullover",
      "cozy sweater",
      "chunky knit",
      "unisex sweater",
      "autumn fashion",
      "gift for her",
      "neutral knitwear",
      "handmade style",
    ],
    categories_etsy: ["Clothing > Unisex Adult Clothing > Sweaters"],
    price: 48.0,
    currency: "USD",
    sku: "SHIRT-KNIT-003",
    pod_provider: "Printify",
    materials: ["wool", "acrylic blend"],
    variants: [{ name: "Size", options: ["S", "M", "L", "XL"] }],
    colors: ["Oatmeal", "Charcoal"],
    sizes: ["S", "M", "L", "XL"],
    images: [`${R2}/wool-scarf-01.jpg`, `${R2}/wool-scarf-02.jpg`],
    mockups: [],
    video_url: null,
    image_provider: "google-imagen",
    image_model: "imagen-3.0-generate-001",
    quality_score: 7.9,
    favorite: false,
    printify_product_id: null,
    etsy_listing_id: null,
    regeneration_requested: null,
    history: [
      { date: "2026-07-14T11:00:00Z", action: "created", actor: "seed", note: "Seed data" },
      { date: "2026-07-16T10:00:00Z", action: "approve", actor: "console", note: "Status Draft -> Approved" },
      { date: "2026-07-17T09:30:00Z", action: "publish", actor: "console", note: "Status Approved -> PublishRequested" },
    ],
  },
  {
    type: "product-listing",
    layer: "products",
    created: "2026-07-13",
    updated: "2026-07-15",
    status: "Rejected",
    slug: "highland-wool-pullover",
    category: "Shirts",
    collection: null,
    store: null,
    title_etsy:
      "Highland Wool Pullover — Rustic Fair Isle Knit Sweater, Nordic Style",
    description_long:
      "A rustic Fair-Isle-patterned pullover in forest and cream. Nordic-inspired, warm and heavyweight. Rejected in review: pattern too close to a trademarked motif — needs a redesign before it can go live.",
    description_short: "Fair Isle knit pullover, forest green & cream.",
    tags: [
      "fair isle sweater",
      "wool pullover",
      "nordic sweater",
      "rustic knit",
      "highland style",
      "winter sweater",
      "cozy knitwear",
      "cream sweater",
      "forest green",
      "heavyweight knit",
    ],
    categories_etsy: ["Clothing > Unisex Adult Clothing > Sweaters"],
    price: 52.0,
    currency: "USD",
    sku: "SHIRT-WOOL-004",
    pod_provider: "Printify",
    materials: ["wool"],
    variants: [{ name: "Size", options: ["M", "L", "XL"] }],
    colors: ["Forest Green", "Cream"],
    sizes: ["M", "L", "XL"],
    images: [`${R2}/wool-scarf-02.jpg`, `${R2}/wool-scarf-01.jpg`],
    mockups: [],
    video_url: null,
    image_provider: "huggingface",
    image_model: "stabilityai/stable-diffusion-xl-base-1.0",
    quality_score: 4.2,
    favorite: false,
    printify_product_id: null,
    etsy_listing_id: null,
    regeneration_requested: "images",
    history: [
      { date: "2026-07-13T13:00:00Z", action: "created", actor: "seed", note: "Seed data" },
      { date: "2026-07-15T16:45:00Z", action: "reject", actor: "console", note: "Status Draft -> Rejected: trademark risk on pattern" },
    ],
  },
  {
    type: "product-listing",
    layer: "products",
    created: "2026-07-10",
    updated: "2026-07-16",
    status: "Published",
    slug: "abstract-horizon-print",
    category: "Wall-Art",
    collection: "Modern Minimalist",
    store: "MySpaceBoats",
    title_etsy:
      "Abstract Horizon Fine Art Print — Modern Minimalist Wall Decor, Terracotta",
    description_long:
      "A serene abstract horizon in terracotta and cream — warm, grounding, gallery-quality. Printed on heavyweight matte fine-art paper. Multiple sizes. Frame not included.",
    description_short: "Minimalist abstract horizon print, terracotta & cream.",
    tags: [
      "abstract print",
      "horizon art",
      "minimalist wall art",
      "terracotta decor",
      "modern print",
      "boho wall art",
      "living room decor",
      "fine art print",
      "neutral art",
      "gallery wall",
    ],
    categories_etsy: ["Art & Collectibles > Prints > Digital Prints"],
    price: 32.0,
    currency: "USD",
    sku: "WALL-HORIZON-005",
    pod_provider: "Printify",
    materials: ["matte fine-art paper"],
    variants: [{ name: "Size", options: ["8x10", "16x20", "24x36"] }],
    colors: ["Terracotta", "Cream"],
    sizes: ["8x10", "16x20", "24x36"],
    images: [`${R2}/wall-art-01.jpg`],
    mockups: [],
    video_url: null,
    image_provider: "workers-ai",
    image_model: "@cf/black-forest-labs/flux-1-schnell",
    quality_score: 9.1,
    favorite: true,
    printify_product_id: "pfy_5f2a91c0",
    etsy_listing_id: "1874500321",
    regeneration_requested: null,
    history: [
      { date: "2026-07-10T09:00:00Z", action: "created", actor: "seed", note: "Seed data" },
      { date: "2026-07-12T10:00:00Z", action: "approve", actor: "console", note: "Status Draft -> Approved" },
      { date: "2026-07-13T09:00:00Z", action: "publish", actor: "console", note: "Status Approved -> PublishRequested" },
      { date: "2026-07-16T12:00:00Z", action: "published", actor: "routine", note: "Published to Etsy by Publishing routine" },
    ],
  },
  {
    type: "product-listing",
    layer: "products",
    created: "2026-07-11",
    updated: "2026-07-17",
    status: "OnHold",
    slug: "golden-ratio-poster",
    category: "Wall-Art",
    collection: null,
    store: null,
    title_etsy:
      "Golden Ratio Sacred Geometry Poster — Nautilus Spiral Art Print, Fibonacci",
    description_long:
      "The Fibonacci spiral rendered as a clean sacred-geometry poster in gold on charcoal. On hold in review pending a check that the geometry overlay is fully original. Heavyweight matte paper.",
    description_short: "Golden ratio / Fibonacci spiral poster, gold on charcoal.",
    tags: [
      "golden ratio",
      "sacred geometry",
      "fibonacci art",
      "nautilus spiral",
      "geometry poster",
      "gold wall art",
      "math art",
      "minimalist poster",
      "charcoal print",
      "spiritual decor",
    ],
    categories_etsy: ["Art & Collectibles > Prints > Digital Prints"],
    price: 28.0,
    currency: "USD",
    sku: "WALL-GOLDEN-006",
    pod_provider: "Printify",
    materials: ["matte fine-art paper"],
    variants: [{ name: "Size", options: ["11x17", "18x24"] }],
    colors: ["Gold", "Charcoal"],
    sizes: ["11x17", "18x24"],
    images: [`${R2}/wall-art-01.jpg`],
    mockups: [],
    video_url: null,
    image_provider: "google-imagen",
    image_model: "imagen-3.0-generate-001",
    quality_score: 6.5,
    favorite: false,
    printify_product_id: null,
    etsy_listing_id: null,
    regeneration_requested: null,
    history: [
      { date: "2026-07-11T15:00:00Z", action: "created", actor: "seed", note: "Seed data" },
      { date: "2026-07-17T11:20:00Z", action: "hold", actor: "console", note: "Status Draft -> OnHold: verify geometry overlay is original" },
    ],
  },
];
