// Data access for the Control Center: reads the Workflow Engine's state
// (Core/state/**, committed to the repo) through the GitHub Contents API —
// same pattern, same client and same safety boundary as the fiche reads in
// lib/data.ts. MOCK_DATA=1 serves a bundled snapshot of REAL pipeline output
// (Web/lib/mock-state.json, regenerated by scripts/build-mock-state.mjs).

import { getFile, listDir, putFile } from "./github";
import { isMockMode } from "./data";
import type {
  EtsyEvent,
  ProductObject,
  QueueTask,
  StateIndex,
  WorkflowState,
} from "./engine-types";
import mockState from "./mock-state.json";

const STATE = "Core/state";

interface MockSnapshot {
  index: StateIndex;
  products: ProductObject[];
  workflows: WorkflowState[];
  events: EtsyEvent[];
  queue: { tasks: QueueTask[] };
}

function mock(): MockSnapshot {
  return mockState as unknown as MockSnapshot;
}

export async function getStateIndex(): Promise<StateIndex | null> {
  if (isMockMode()) return mock().index;
  const file = await getFile(`${STATE}/index.json`);
  return file ? (JSON.parse(file.content) as StateIndex) : null;
}

export async function getProducts(): Promise<ProductObject[]> {
  if (isMockMode()) return mock().products;
  const entries = await listDir(`${STATE}/products`);
  const out: ProductObject[] = [];
  for (const e of entries.filter((e) => e.type === "file" && e.name.endsWith(".json"))) {
    const f = await getFile(e.path);
    if (f) out.push(JSON.parse(f.content) as ProductObject);
  }
  return out;
}

export async function getProduct(id: string): Promise<ProductObject | null> {
  if (isMockMode()) return mock().products.find((p) => p.id === id || p.slug === id) ?? null;
  const f = await getFile(`${STATE}/products/${id.startsWith("prod_") ? id : `prod_${id}`}.json`);
  return f ? (JSON.parse(f.content) as ProductObject) : null;
}

export async function getWorkflows(): Promise<WorkflowState[]> {
  if (isMockMode()) return mock().workflows;
  const entries = await listDir(`${STATE}/workflows`);
  const out: WorkflowState[] = [];
  for (const e of entries.filter((e) => e.type === "file" && e.name.endsWith(".json"))) {
    const f = await getFile(e.path);
    if (f) out.push(JSON.parse(f.content) as WorkflowState);
  }
  return out;
}

export async function getWorkflow(id: string): Promise<WorkflowState | null> {
  if (isMockMode()) return mock().workflows.find((w) => w.id === id) ?? null;
  const f = await getFile(`${STATE}/workflows/${id}.json`);
  return f ? (JSON.parse(f.content) as WorkflowState) : null;
}

export async function getRecentEvents(limit = 120): Promise<EtsyEvent[]> {
  if (isMockMode()) return mock().events.slice(0, limit);
  const entries = await listDir(`${STATE}/events`);
  const files = entries
    .filter((e) => e.type === "file" && e.name.endsWith(".ndjson"))
    .sort((a, b) => b.name.localeCompare(a.name));
  const out: EtsyEvent[] = [];
  for (const e of files) {
    const f = await getFile(e.path);
    if (!f) continue;
    const lines = f.content.trim().split("\n");
    for (let i = lines.length - 1; i >= 0 && out.length < limit; i--) {
      if (lines[i]) out.push(JSON.parse(lines[i]) as EtsyEvent);
    }
    if (out.length >= limit) break;
  }
  return out;
}

export async function getQueue(): Promise<QueueTask[]> {
  if (isMockMode()) return mock().queue.tasks;
  const f = await getFile(`${STATE}/queue/tasks.json`);
  return f ? (JSON.parse(f.content) as { tasks: QueueTask[] }).tasks : [];
}

// The console's ONLY write into engine territory: append an intent task to the
// queue file. The engine (Claude Code / a GitHub Actions routine) is the sole
// executor — exactly the same boundary as the fiche status writes: the web
// tier requests, it never performs.
export async function enqueueTask(
  kind: "resume-workflow" | "retry-step" | "run-pipeline",
  payload: Record<string, unknown>,
): Promise<QueueTask> {
  const now = new Date().toISOString();
  const task: QueueTask = {
    id: `task_${Date.now()}_web`,
    kind,
    payload,
    status: "pending",
    attempts: 0,
    maxAttempts: 3,
    createdAt: now,
    updatedAt: now,
    lastError: null,
  };
  if (isMockMode()) return task; // no backing store in mock — optimistic echo
  const path = `${STATE}/queue/tasks.json`;
  const f = await getFile(path);
  const file = f ? (JSON.parse(f.content) as { tasks: QueueTask[] }) : { tasks: [] };
  file.tasks.push(task);
  await putFile(path, JSON.stringify(file, null, 2) + "\n", f?.sha ?? null, `web: enqueue ${kind}`);
  return task;
}
